export const productsList = [
  // food
  {
    title: 'Water',
    description: '',
    category: 'FOOD/WATER',
    img: '../../../assets/decks/logistics/products/Water.png',
    quantity: 0,
    units: 'Liters',
  },
  {
    title: 'Rice',
    description: '',
    category: 'FOOD/WATER',
    img: '../../../assets/decks/logistics/products/RiceSack.png',
    quantity: 0,
    units: 'Kgs',
  },
  {
    title: 'Ready to Eat Meals',
    description: '',
    category: 'FOOD/WATER',
    img: '../../../assets/decks/logistics/products/ReadytoEatMeals.png',
    quantity: 0,
    descriptionPlaceholder:
      'Add description. E.g. instant porridge, bread, biscuits, nasi bungkus/padang',
    hasDescription: true,
    units: 'Packs',
  },
  {
    title: 'Sembako',
    description: '',
    category: 'FOOD/WATER',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    units: 'Packs',
  },
  {
    title: 'Fresh Produce',
    description: '',
    category: 'FOOD/WATER',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    descriptionPlaceholder:
      'Add description. E.g. (Eggs, Vegetables, Meat, Fruits)',
    hasDescription: true,
    units: 'Kgs',
  },
  {
    title: 'Baby Food',
    description: '',
    category: 'FOOD/WATER',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    units: 'Packs',
  },

  // CLOTHES & SELF PROTECTION KIT
  {
    title: 'Women',
    description: '',
    category: 'CLOTHES & SELF PROTECTION KIT',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    descriptionPlaceholder: 'Add description. E.g. Underwear, Bra, Dress',
    hasDescription: true,
    units: 'Pcs',
  },
  {
    title: 'Men',
    description: '',
    category: 'CLOTHES & SELF PROTECTION KIT',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    descriptionPlaceholder: 'Add description: E.g. Shirts, Pants, Underwear',
    hasDescription: true,
    units: 'Pcs',
  },
  {
    title: 'Footwear',
    description: '',
    category: 'CLOTHES & SELF PROTECTION KIT',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    descriptionPlaceholder: 'Add description: E.g. Sandals, Protective Boots',
    hasDescription: true,
    units: 'Pairs',
  },
  {
    title: 'Face Masks',
    description: '',
    category: 'CLOTHES & SELF PROTECTION KIT',
    img: '../../../assets/decks/logistics/products/Mask.png',
    quantity: 0,
    units: 'Pcs',
  },
  {
    title: 'Protective Eye Wear',
    description: '',
    category: 'CLOTHES & SELF PROTECTION KIT',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    units: 'Pcs',
  },
  {
    title: 'Raincoats',
    description: '',
    category: 'CLOTHES & SELF PROTECTION KIT',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    units: 'Pcs',
  },

  // BABIES AND CHILDREN

  {
    title: 'Clothing',
    description: '',
    category: 'BABIES AND CHILDREN',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    descriptionPlaceholder: 'Add description. E.g age/size, clothing item',
    hasDescription: true,
    units: 'Pcs',
  },
  {
    title: 'Bottles',
    description: '',
    category: 'BABIES AND CHILDREN',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    units: 'Pcs',
  },
  {
    title: 'Toys',
    description: '',
    category: 'BABIES AND CHILDREN',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    units: 'Pcs',
  },
  {
    title: 'Pacifier',
    description: '',
    category: 'BABIES AND CHILDREN',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    units: 'Pcs',
  },

  // HOUSEHOLD AND EMERGENCY SUPPLIES
  {
    title: 'Utensils',
    description: '',
    category: 'HOUSEHOLD AND EMERGENCY SUPPLIES',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    descriptionPlaceholder: 'Add description. E.g pan, cutlery',
    hasDescription: true,
    units: 'Pcs',
  },
  {
    title: 'Blankets',
    description: '',
    category: 'HOUSEHOLD AND EMERGENCY SUPPLIES',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    units: 'Pcs',
  },
  {
    title: 'Sleeping Mats',
    description: '',
    category: 'HOUSEHOLD AND EMERGENCY SUPPLIES',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    units: 'Pcs',
  },
  {
    title: 'Cleaning Supplies',
    description: '',
    category: 'HOUSEHOLD AND EMERGENCY SUPPLIES',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    descriptionPlaceholder:
      'Add description. (E.g. Brooms, Detergent, Floor Wiper)',
    hasDescription: true,
    units: 'Pcs',
  },

  {
    title: 'Flashlight',
    description: '',
    category: 'HOUSEHOLD AND EMERGENCY SUPPLIES',
    img: '../../../assets/decks/logistics/products/Flashlight.png',
    quantity: 0,
    units: 'Pcs',
  },

  // PERSONAL HEALTH
  {
    title: 'First aid kit',
    description: '',
    category: 'PERSONAL HEALTH',
    img: '../../../assets/decks/logistics/products/Firstaid.png',
    quantity: 0,
    units: 'Pcs',
  },
  {
    title: 'Diarrhea Medication',
    description: '',
    category: 'PERSONAL HEALTH',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    units: 'Strips',
  },
  {
    title: 'Anti Fungal Cream',
    description: '',
    category: 'PERSONAL HEALTH',
    img: '../../../assets/decks/logistics/products/AntiFungalCream.png',
    quantity: 0,
    units: 'Pcs',
  },
  {
    title: 'Vitamins & Supplements',
    description: '',
    category: 'PERSONAL HEALTH',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    descriptionPlaceholder:
      'Add description. (E.g. Iron Supplement, Multi vitamin, Vitamin C)',
    hasDescription: true,
    units: 'Strips',
  },
  {
    title: 'Paracetamol',
    description: '',
    category: 'PERSONAL HEALTH',
    img: '../../../assets/decks/logistics/products/Paracetamol.png',
    quantity: 0,
    units: 'Strips',
  },
  {
    title: 'Eucalyptus Oil',
    description: '',
    category: 'PERSONAL HEALTH',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    units: 'Bottles',
  },
  {
    title: 'Personal Health Equipment',
    description: '',
    category: 'PERSONAL HEALTH',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    descriptionPlaceholder:
      'Add description E.g. Wheelchair, walking stick, oxygen, blood pressure measurement tool, diabetes measurement tool, inhaler',
    hasDescription: true,
    units: 'Pcs',
  },
  // HYGIENE KITS

  {
    title: 'Female Hygiene Products',
    description: '',
    category: 'HYGIENE KITS',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    descriptionPlaceholder:
      'Add description. E.g. pads, tampons, menstrual cups',
    hasDescription: true,
    units: 'Pcs',
  },
  {
    title: 'Oral Care',
    description: '',
    category: 'HYGIENE KITS',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    descriptionPlaceholder: 'Add description. E.g. toothbrush, toothpaste',
    hasDescription: true,
    units: 'Pcs',
  },
  {
    title: 'Personal Cleansing',
    description: '',
    category: 'HYGIENE KITS',
    img: '../../../assets/decks/logistics/products/no-pictures.png',
    quantity: 0,
    descriptionPlaceholder: 'Add description. E.g. soap, shampoo',
    hasDescription: true,
    units: 'Pcs',
  },
];
